baseurl = "/"
languageCode = "en-us"
title = "BIMS 8382"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

  [permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Syllabus"
    url = "/about/"
[[menu.main]]
    name = "Week 1"
    url = "/Week 1 - Intro/Week_1_Intro.html/"
[[menu.main]]
    name = "Week 2"
    url = "https://twitter.com/rstudio"
    [[menu.main]]
    name = "Week 3"
    url = "https://github.com/rstudio/blogdown"
[[menu.main]]
    name = "Week 4"
    url = "https://twitter.com/rstudio"
[[menu.main]]
    name = "Week 5"
    url = "https://github.com/rstudio/blogdown"
[[menu.main]]
    name = "Week 6"
    url = "https://twitter.com/rstudio"
[[menu.main]]
    name = "Week 7"
    url = "https://twitter.com/rstudio"

[params]
    description = "BIMS 8382."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "images/favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

